#ifndef DEFINES_H
#define DEFINES_H

enum CPOINTS_PUSH {CPOINTS_PUSH_OK, CPOINTS_PUSH_NO_SPACE, CPOINTS_PUSH_NOT_ALL};
enum CMARKEDPOINT_FLAG {CMARKEDPOINT_FLAG_NO_SELECT, CMARKEDPOINT_FLAG_SELECT};

#endif
